services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://new:1234@cluster0.pcjwc.mongodb.net/
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    command: npm run dev -- --host

  server-test:
    build:
      context: ./server
      target: test
    volumes:
      - ./server:/app
    command: npm test

  client-test:
    build:
      context: ./client
      target: test
    volumes:
      - ./client:/app
    command: npm test
