services:
  server:
    build:
      context: ./Server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://new:1234@cluster0.pcjwc.mongodb.net/
    volumes:
      - ./Server:/app
      - /app/node_modules
    command: npm run dev

  client:
    build:
      context: ./Client
    ports:
      - "5173:5173"
    depends_on:
      - server
    command: npm run dev -- --host

  server-test:
    build:
      context: ./Server
      target: test
    volumes:
      - ./Server:/app
    command: npm test

  client-test:
    build:
      context: ./Client
      target: test
    volumes:
      - ./Client:/app
    command: npm test
