name: CI testing Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        docker --version
        docker compose version || sudo apt-get install docker-compose

    - name: Build and Start Services
      run: |
        docker-compose up -d
